import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Aqar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="md:px-12">
        <Navbar />
        <main className="md:max-w-7xl min-w-[250px] mx-auto">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
